In [2]:
import pandas as pd

In [3]:
# Load the Excel file into a DataFrame
df = pd.read_excel('train.xlsx', sheet_name=0)
df

,ID,Tank Failure Pressure (bar),Liquid Ratio (%),Tank Width (m),Tank Length (m),Tank Height (m),Height of BLEVE (m),Tank Height with Gas (m),Vapour Temerature (K),Liquid Temerature (K),Status,Stand-off Distance,Target
0,B291,13.6,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,Superheated,5,0.012166
1,B291,13.6,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,Superheated,6,0.014556
2,B291,13.6,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,Superheated,7,0.017034
3,B291,13.6,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,Superheated,8,0.019576
4,B291,13.6,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,Superheated,9,0.022172
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21595,B103,30.7,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,Subcooled,36,0.093782
21596,B103,30.7,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,Subcooled,37,0.096635
21597,B103,30.7,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,Subcooled,38,0.099487
21598,B103,30.7,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,Subcooled,39,0.102341
21599,B103,30.7,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,Subcooled,40,0.105201

In [4]:
# Create a sample DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Duplicate the DataFrame 5 times
df_duplicates = [df.copy() for _ in range(5)]

# Concatenate the duplicates
df_combined = pd.concat(df_duplicates)

print(df_combined)

   A  B
0  1  4
1  2  5
2  3  6
0  1  4
1  2  5
2  3  6
0  1  4
1  2  5
2  3  6
0  1  4
1  2  5
2  3  6
0  1  4
1  2  5
2  3  6

In [5]:
df_duplicates

[   A  B
 0  1  4
 1  2  5
 2  3  6,
    A  B
 0  1  4
 1  2  5
 2  3  6,
    A  B
 0  1  4
 1  2  5
 2  3  6,
    A  B
 0  1  4
 1  2  5
 2  3  6,
    A  B
 0  1  4
 1  2  5
 2  3  6]