In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Split The Dataset FIRST to prevent leaking information

In [81]:
# Load the Excel file into a DataFrame
df = pd.read_excel('BLEVE_Open_500Butan_500Propane_5-40m_8outputs.xlsx', sheet_name=3)
# df.iloc[:,11:]
df

,ID,Tank Failure Pressure (bar),Liquid Ratio (%),Tank Width (m),Tank Length (m),Tank Height (m),Height of BLEVE (m),Tank Height with Gas (m),Vapour Temerature (K),Liquid Temerature (K),...,31,32,33,34,35,36,37,38,39,40
0,B1,24.500000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,...,0.013912,0.014028,0.014140,0.014237,0.014318,0.014396,0.014451,0.014483,0.014492,0.014431
1,B2,30.300000,0.577797,1.4,8.8,2.4,0.6,1.0,382.5,398.7,...,0.015540,0.015727,0.015880,0.015988,0.016085,0.016196,0.016330,0.016497,0.016685,0.016867
2,B3,9.900000,0.183542,2.8,8.4,1.6,0.8,1.4,420.4,307.7,...,0.016833,0.016932,0.017026,0.017146,0.017298,0.017486,0.017677,0.017832,0.017942,0.018027
3,B4,21.000000,0.428973,1.0,6.0,0.4,1.6,0.2,302.8,320.4,...,0.007566,0.007644,0.007727,0.007803,0.007888,0.007960,0.008039,0.008118,0.008186,0.008262
4,B5,13.600000,0.612155,2.8,7.6,0.6,1.6,0.4,376.8,384.0,...,0.014785,0.014921,0.015052,0.015177,0.015303,0.015421,0.015540,0.015662,0.015784,0.015915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,P496,12.996290,0.218564,2.2,8.8,1.8,1.6,1.4,447.7,308.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,P497,8.070722,0.170783,0.8,9.4,2.6,1.6,2.2,318.7,351.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,P498,18.609730,0.789021,1.2,4.6,1.4,2.0,0.2,399.7,302.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,P499,39.943390,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,P500,11.402390,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
# detecting NAN rows

mask = df.isna().any(axis=1)

na_row = df[mask]
na_row

,ID,Tank Failure Pressure (bar),Liquid Ratio (%),Tank Width (m),Tank Length (m),Tank Height (m),Height of BLEVE (m),Tank Height with Gas (m),Vapour Temerature (K),Liquid Temerature (K),...,31,32,33,34,35,36,37,38,39,40
800,P301,11.785080,0.393567,1.6,8.2,2.6,0.4,1.6,385.5,347.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
801,P302,10.287280,0.203799,1.8,9.8,1.0,1.6,0.8,380.5,358.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
802,P303,33.041270,0.264174,1.6,4.2,0.4,0.2,0.2,312.1,334.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
803,P304,11.626690,0.518494,2.2,7.4,1.4,0.4,0.8,419.1,326.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
804,P305,39.703970,0.676665,2.2,8.8,3.0,1.0,1.0,315.2,338.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,P496,12.996290,0.218564,2.2,8.8,1.8,1.6,1.4,447.7,308.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,P497,8.070722,0.170783,0.8,9.4,2.6,1.6,2.2,318.7,351.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,P498,18.609730,0.789021,1.2,4.6,1.4,2.0,0.2,399.7,302.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,P499,39.943390,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,P500,11.402390,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
# Lucky, the row which has nan is the last 200 rows, so we can drop all last 200 rows for all other sheets

# df_full = df.dropna()
df_full = df.iloc[:800,:]
df_full

,ID,Tank Failure Pressure (bar),Liquid Ratio (%),Tank Width (m),Tank Length (m),Tank Height (m),Height of BLEVE (m),Tank Height with Gas (m),Vapour Temerature (K),Liquid Temerature (K),...,31,32,33,34,35,36,37,38,39,40
0,B1,24.500000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,...,0.013912,0.014028,0.014140,0.014237,0.014318,0.014396,0.014451,0.014483,0.014492,0.014431
1,B2,30.300000,0.577797,1.4,8.8,2.4,0.6,1.0,382.5,398.7,...,0.015540,0.015727,0.015880,0.015988,0.016085,0.016196,0.016330,0.016497,0.016685,0.016867
2,B3,9.900000,0.183542,2.8,8.4,1.6,0.8,1.4,420.4,307.7,...,0.016833,0.016932,0.017026,0.017146,0.017298,0.017486,0.017677,0.017832,0.017942,0.018027
3,B4,21.000000,0.428973,1.0,6.0,0.4,1.6,0.2,302.8,320.4,...,0.007566,0.007644,0.007727,0.007803,0.007888,0.007960,0.008039,0.008118,0.008186,0.008262
4,B5,13.600000,0.612155,2.8,7.6,0.6,1.6,0.4,376.8,384.0,...,0.014785,0.014921,0.015052,0.015177,0.015303,0.015421,0.015540,0.015662,0.015784,0.015915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,P296,17.607220,0.341589,0.6,3.8,0.8,0.4,0.6,444.3,318.5,...,0.007766,0.007847,0.007922,0.008010,0.008081,0.008161,0.008239,0.008313,0.008384,0.008465
796,P297,7.207576,0.882472,2.8,7.4,2.0,1.8,0.4,425.1,309.0,...,0.014846,0.014991,0.015122,0.015238,0.015364,0.015483,0.015611,0.015736,0.015863,0.015982
797,P298,8.004843,0.446105,2.8,3.4,1.8,0.2,1.0,315.7,298.4,...,0.017449,0.017262,0.017077,0.016918,0.016817,0.016779,0.016785,0.016862,0.016983,0.017164
798,P299,11.429500,0.223003,2.8,0.8,0.6,1.8,0.6,435.2,347.9,...,0.008228,0.008310,0.008395,0.008477,0.008556,0.008633,0.008713,0.008790,0.008869,0.008935
799,P300,33.173770,0.372041,1.0,2.2,0.6,0.2,0.4,312.7,318.2,...,0.011608,0.011729,0.011845,0.011959,0.012066,0.012178,0.012275,0.012374,0.012477,0.012573

In [67]:
df_train, df_test = train_test_split(df_full, test_size=0.25, random_state=42)   # with random state, all sheets will be splitted in the same way

df_train

,ID,Tank Failure Pressure (bar),Liquid Ratio (%),Tank Width (m),Tank Length (m),Tank Height (m),Height of BLEVE (m),Tank Height with Gas (m),Vapour Temerature (K),Liquid Temerature (K),...,31,32,33,34,35,36,37,38,39,40
290,B291,13.60000,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,...,0.007774,0.007837,0.007903,0.007970,0.008046,0.008118,0.008181,0.008250,0.008323,0.008388
158,B159,16.90000,0.229274,2.4,1.6,2.6,1.2,2.2,391.1,410.7,...,0.014833,0.014882,0.014996,0.015197,0.015465,0.015741,0.015921,0.016004,0.016057,0.016082
69,B70,31.80000,0.139025,3.0,1.6,1.2,1.4,1.0,404.9,339.6,...,0.015826,0.015866,0.015954,0.016111,0.016345,0.016624,0.016832,0.016927,0.016971,0.016998
517,P18,33.67886,0.510511,2.6,7.4,1.4,1.6,0.8,325.1,364.8,...,0.018781,0.020215,0.020191,0.020053,0.019891,0.019718,0.019565,0.019438,0.019364,0.019374
131,B132,21.20000,0.105022,1.6,9.6,2.2,0.6,2.0,529.5,306.6,...,0.016284,0.016196,0.016185,0.016413,0.019046,0.018869,0.018673,0.018474,0.018281,0.018099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,B72,20.20000,0.585372,2.6,6.0,1.2,1.8,0.4,336.9,290.3,...,0.014324,0.014464,0.014603,0.014718,0.014819,0.014913,0.014989,0.015065,0.015128,0.015170
106,B107,15.30000,0.693403,2.8,7.0,1.4,0.4,0.4,329.5,360.7,...,0.015902,0.016104,0.016223,0.016284,0.016336,0.016385,0.016450,0.016538,0.016651,0.016791
270,B271,9.50000,0.792603,2.8,0.6,1.0,1.8,0.2,525.0,326.3,...,0.007825,0.007893,0.007957,0.008021,0.008080,0.008140,0.008194,0.008256,0.008311,0.008363
435,B436,27.00000,0.215370,1.8,3.8,0.6,0.0,0.6,336.4,412.5,...,0.014424,0.014565,0.014741,0.014906,0.015050,0.015157,0.015249,0.015338,0.015426,0.015527
102,B103,30.70000,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,...,0.011290,0.011419,0.011536,0.011659,0.011785,0.011906,0.012024,0.012137,0.012256,0.012363

In [68]:
df.columns[:11]

Index(['ID', 'Tank Failure Pressure (bar)', 'Liquid Ratio (%)',
       'Tank Width (m)', 'Tank Length (m)', 'Tank Height (m)',
       'Height of BLEVE (m)', 'Tank Height with Gas (m)',
       ' Vapour Temerature (K)', ' Liquid Temerature (K)', 'Status'],
      dtype='object')

In [70]:
df = df_train

In [71]:
# Create a new DataFrame to store the split rows
df_out = pd.DataFrame(columns=df.columns[:11])


# Iterate over the rows in the original DataFrame
for i in range(len(df)):
    for col in range(11, 47):
        # create a copy of the input DataFrame with only the first 11 columns and the current column, this takes all data-points
        df_col = df.iloc[:, list(range(11)) + [col]].copy()
        # rename the current column to "Target"
        df_col = df_col.rename(columns={df_col.columns[-1]: 'Target'})
        # repeat each row and append to the output DataFrame, we only refer to the current row i
        # df_out = df_out.append(df_col.iloc[[i]].reset_index(drop=True), ignore_index=True)            # append is deprecated
        df_out = pd.concat([df_out, df_col.iloc[[i]]], ignore_index=True)

In [1]:
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [72]:
df_out

,ID,Tank Failure Pressure (bar),Liquid Ratio (%),Tank Width (m),Tank Length (m),Tank Height (m),Height of BLEVE (m),Tank Height with Gas (m),Vapour Temerature (K),Liquid Temerature (K),Status,Target
0,B291,13.6,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,Superheated,0.005043
1,B291,13.6,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,Superheated,0.005543
2,B291,13.6,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,Superheated,0.006014
3,B291,13.6,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,Superheated,0.006445
4,B291,13.6,0.665119,1.0,4.0,0.8,1.8,0.4,435.0,372.5,Superheated,0.006840
...,...,...,...,...,...,...,...,...,...,...,...,...
21595,B103,30.7,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,Subcooled,0.011906
21596,B103,30.7,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,Subcooled,0.012024
21597,B103,30.7,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,Subcooled,0.012137
21598,B103,30.7,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,Subcooled,0.012256
21599,B103,30.7,0.181290,0.6,2.0,2.8,1.2,2.2,334.7,404.9,Subcooled,0.012363

In [62]:
df_out.to_csv("Check.csv",index=False)

# Automated Scripts

In [2]:
from sklearn.model_selection import train_test_split
import pandas as pd

In [4]:
writer_1 = pd.ExcelWriter('train.xlsx', engine='xlsxwriter')
writer_2 = pd.ExcelWriter('test.xlsx', engine='xlsxwriter')


target_name = ['positive_peak_time', 'negative_peak_time', 'arrival_time', 'positive_duration', 'negative_duration', 'positive_pressure', 'negative_pressure', 'positive_impulse']
for k in target_name:
    # Load the Excel file into a DataFrame
    df_read = pd.read_excel('BLEVE_Open_500Butan_500Propane_5-40m_8outputs.xlsx', sheet_name=k)
    df_full = df_read.iloc[:800,:]
    df_train, df_test = train_test_split(df_full, test_size=0.25, random_state=42)   # with random state, all sheets will be splitted in the same way


    df = df_train
    # Create a new DataFrame to store the split rows
    df_out = pd.DataFrame(columns=df.columns[:11])

    # Iterate over the rows in the original DataFrame
    for i in range(len(df)):
        for col in range(11, 47):
            # create a copy of the input DataFrame with only the first 11 columns and the current column, this takes all data-points
            df_col = df.iloc[:, list(range(11)) + [col]].copy()
            # rename the current column to "Target"
            df_col = df_col.rename(columns={df_col.columns[-1]: 'Target'})
            # repeat each row and append to the output DataFrame, we only refer to the current row i
            # df_out = df_out.append(df_col.iloc[[i]].reset_index(drop=True), ignore_index=True)            # append is deprecated
            df_out = pd.concat([df_out, df_col.iloc[[i]]], ignore_index=True)

    numbers = list(range(5,41))*600
    df_out["Stand-off Distance"] = numbers

    # swap the position of the 12th and 13th columns
    df_out.iloc[:, [11, 12]] = df_out.iloc[:, [12, 11]].to_numpy()    # convert column 12,11 into a 2-D numpy array to overwrite and overwrite them
    # Swap the column name
    df_out.columns = list(df_out.columns[:11]) + ['Stand-off Distance', 'Target']
    #Save
    
    df_out.to_excel(writer_1,index=False, sheet_name=k)
    


    #############################################################
    #############################################################

    df = df_test
    # Create a new DataFrame to store the split rows
    df_out = pd.DataFrame(columns=df.columns[:11])

    # Iterate over the rows in the original DataFrame
    for i in range(len(df)):
        for col in range(11, 47):
            # create a copy of the input DataFrame with only the first 11 columns and the current column, this takes all data-points
            df_col = df.iloc[:, list(range(11)) + [col]].copy()
            # rename the current column to "Target"
            df_col = df_col.rename(columns={df_col.columns[-1]: 'Target'})
            # repeat each row and append to the output DataFrame, we only refer to the current row i
            # df_out = df_out.append(df_col.iloc[[i]].reset_index(drop=True), ignore_index=True)            # append is deprecated
            df_out = pd.concat([df_out, df_col.iloc[[i]]], ignore_index=True)


    numbers = list(range(5,41))*200
    df_out["Stand-off Distance"] = numbers

    # swap the position of the 12th and 13th columns
    df_out.iloc[:, [11, 12]] = df_out.iloc[:, [12, 11]].to_numpy()    # convert column 12,11 into a 2-D numpy array to overwrite and overwrite them
    # Swap the column name
    df_out.columns = list(df_out.columns[:11]) + ['Stand-off Distance', 'Target']
    #Save
    df_out.to_excel(writer_2,index=False, sheet_name=k)

writer_1.save()
writer_2.save()

___

# Add extra stand-off distance to column  (Already Added to the loop above)

In [7]:
numbers = list(range(5,41))*1000
# print(numbers)
print(len(numbers))

36000

In [75]:
k = "arrival_time"
df = pd.read_csv(k + ".csv")
df

,ID,Tank Failure Pressure (bar),Liquid Ratio (%),Tank Width (m),Tank Length (m),Tank Height (m),Height of BLEVE (m),Tank Height with Gas (m),Vapour Temerature (K),Liquid Temerature (K),Status,Target
0,B1,24.50000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,Subcooled,0.010208
1,B1,24.50000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,Subcooled,0.012350
2,B1,24.50000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,Subcooled,0.014577
3,B1,24.50000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,Subcooled,0.016878
4,B1,24.50000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,Subcooled,0.019250
...,...,...,...,...,...,...,...,...,...,...,...,...
35995,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.091749
35996,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.094536
35997,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.097317
35998,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.100105
35999,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.102896

In [76]:
df["Stand-off Distance"] = numbers

In [77]:
df

,ID,Tank Failure Pressure (bar),Liquid Ratio (%),Tank Width (m),Tank Length (m),Tank Height (m),Height of BLEVE (m),Tank Height with Gas (m),Vapour Temerature (K),Liquid Temerature (K),Status,Target,Stand-off Distance
0,B1,24.50000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,Subcooled,0.010208,5
1,B1,24.50000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,Subcooled,0.012350,6
2,B1,24.50000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,Subcooled,0.014577,7
3,B1,24.50000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,Subcooled,0.016878,8
4,B1,24.50000,0.519805,2.2,6.0,1.0,1.6,0.4,307.8,339.0,Subcooled,0.019250,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.091749,36
35996,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.094536,37
35997,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.097317,38
35998,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.100105,39
35999,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.102896,40

In [78]:
df.tail(72)

,ID,Tank Failure Pressure (bar),Liquid Ratio (%),Tank Width (m),Tank Length (m),Tank Height (m),Height of BLEVE (m),Tank Height with Gas (m),Vapour Temerature (K),Liquid Temerature (K),Status,Target,Stand-off Distance
35928,P499,39.94339,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,Subcooled,0.009318,5
35929,P499,39.94339,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,Subcooled,0.011154,6
35930,P499,39.94339,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,Subcooled,0.013088,7
35931,P499,39.94339,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,Subcooled,0.015112,8
35932,P499,39.94339,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,Subcooled,0.017221,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.091749,36
35996,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.094536,37
35997,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.097317,38
35998,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.100105,39
35999,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,0.102896,40

In [79]:
# swap the position of the 12th and 13th columns
df.iloc[:, [11, 12]] = df.iloc[:, [12, 11]].to_numpy()    # convert column 12,11 into a 2-D numpy array to overwrite and overwrite them
# Swap the column name
df.columns = list(df.columns[:11]) + ['Stand-off Distance', 'Target']
df.tail(72)

,ID,Tank Failure Pressure (bar),Liquid Ratio (%),Tank Width (m),Tank Length (m),Tank Height (m),Height of BLEVE (m),Tank Height with Gas (m),Vapour Temerature (K),Liquid Temerature (K),Status,Stand-off Distance,Target
35928,P499,39.94339,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,Subcooled,5.0,0.009318
35929,P499,39.94339,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,Subcooled,6.0,0.011154
35930,P499,39.94339,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,Subcooled,7.0,0.013088
35931,P499,39.94339,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,Subcooled,8.0,0.015112
35932,P499,39.94339,0.551123,0.6,8.4,2.0,2.0,0.8,405.0,354.3,Subcooled,9.0,0.017221
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35995,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,36.0,0.091749
35996,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,37.0,0.094536
35997,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,38.0,0.097317
35998,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,39.0,0.100105
35999,P500,11.40239,0.442321,1.4,2.8,1.2,1.4,0.8,388.2,366.7,Superheated,40.0,0.102896

In [80]:
df.to_csv(f"{k}_COMPLETE.csv",index=False)